[program:comexcare-horizon]
process_name=%(program_name)s
command=php /var/www/comexcare/artisan horizon
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/comexcare/storage/logs/horizon.log
stopwaitsecs=3600
;numberprocs=1
;maxmemory=128M

[program:comexcare-queue-distributions]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/comexcare/artisan queue:work redis --queue=distributions --sleep=3 --tries=3 --timeout=300
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/comexcare/storage/logs/queue-distributions.log
stopwaitsecs=3600
numprocs=5
;maxmemory=128M

[program:comexcare-queue-distribution]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/comexcare/artisan queue:work redis --queue=distribution --sleep=3 --tries=3 --timeout=300
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/comexcare/storage/logs/queue-distribution.log
stopwaitsecs=3600
numprocs=5

[program:comexcare-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/comexcare/artisan queue:work redis --queue=default --sleep=3 --tries=3
autostart=true
autorestart=true
startretries=3
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/comexcare/storage/logs/queue-default.log
stopwaitsecs=3600
numprocs=5
;maxmemory=128M
