[program:socket-io]
process_name=%(program_name)s
command=node %(here)s/socket-server.cjs
directory=%(here)s
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=%(here)s/storage/logs/socket-io-supervisor.log
stopwaitsecs=10
